# Generated by Django 5.1 on 2024-08-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=63)),
                ('model', models.CharField(max_length=127)),
                ('fuel_type', models.CharField(choices=[('бензин', 'Petrol'), ('дизель', 'Diesel'), ('электричество', 'Electric'), ('гибрид', 'Hybrid')], max_length=31)),
                ('transmission_type', models.CharField(choices=[('механическая', 'Manual'), ('автоматическая', 'Auto'), ('вариатор', 'Cvt'), ('робот', 'Semi Auto')], max_length=31)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
